version: '3'
services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        ports: 
            - "8080:80"
        volumes:
            - ./config:/etc/gitlab
            - ./logs:/var/log/gitlab
            - ./data:/var/opt/gitlab
